-- Recon- cards + R18/edgy expansion

-- ============================================================
-- SHADOW CARDS — Recon- specific
-- ============================================================
INSERT INTO cah_shadow_cards (text, picks) VALUES
  ('Recon- has been "scouting enemy positions" for six hours. He''s actually just _______.', 1),
  ('The secret behind every one of Recon-''s war victories: _______.', 1),
  ('Recon-''s faction application listed three skills: stealth, tactics, and _______.', 1),
  ('Nobody knows how Recon- made it to Archon. The leading theory is _______.', 1),
  ('Recon- was given one job. He showed up four hours late carrying _______.', 1),
  ('The intelligence Recon- gathered on the enemy faction turned out to be mostly _______.', 1),
  ('Recon- was caught in the faction vault. His official excuse: "_______.".', 1),
  ('Leadership promoted Recon- to Archon after he successfully _______.', 1),
  ('Recon-''s scouting report was three pages long. Two pages were about _______.', 1),
  ('Before every mission, Recon- insists on _______.  Nobody stops him anymore.', 1),

-- ============================================================
-- SHADOW CARDS — R18 / edgy / member-specific
-- ============================================================
  ('The thing VirginPimp69 is definitely not a virgin at: _______.', 1),
  ('girlsauce was asked to explain their username. The faction Discord went silent for _______.', 1),
  ('Thegimp13 insists the "13" refers to _______.', 1),
  ('HotChickOG earned that title by _______.', 1),
  ('The faction safe word is "_______". It has been used four times this month.', 1),
  ('During the last faction party, someone suggested _______. It was Atomicc. Nobody was surprised.', 1),
  ('The new recruit listed _______ under "special skills". They were hired on the spot.', 1),
  ('The secret faction Discord channel''s pinned message is just "_______".', 1),
  ('Leadership''s HR policy explicitly prohibits _______ after what happened last time.', 1),
  ('TugaRambo chose the worst possible moment to announce _______. It was mid-war.', 1),
  ('What happens in the faction hotel room stays there. Except for _______.', 1),
  ('The Occultus initiation involves three shots of tequila and _______.', 1),
  ('Faction rule #69: under no circumstances shall any member _______.', 1),
  ('The most disturbing item found during the armoury audit: _______.', 1),
  ('The darkest entry in Torn City''s criminal record this year: _______.', 1),
  ('Torn City''s underground black market best-seller: _______.', 1),
  ('The thing that would get you instantly kicked from Occultus: _______. Ask Night-Fury.', 1),
  ('Torn City crime of the decade: _______ with intent to _______.', 2),
  ('The Occultus blood ritual requires three things: candles, a willing participant, and _______.', 1),
  ('After the war ended, the enemy faction filed a formal complaint about _______. It was about Recon-.', 1),
  ('SnoopDoggyDogg''s pre-chain ritual involves _______ and absolutely no questions.', 1),
  ('The faction member who keeps "accidentally" attacking allies has been identified as _______.', 1),
  ('Viola_ sent a faction-wide DM at 2am. It just said "_______". Six people left the server.', 1),
  ('Onenutwonder420 was asked what the "wonder" refers to. They said _______.', 1),
  ('The thing Recon- and KillroyJenkins agreed to never speak of again: _______.', 1),
  ('Torn City''s prison system was designed to rehabilitate criminals. Instead it created _______.', 1),
  ('The faction therapist''s notes from last Tuesday''s session are entirely about _______.', 1),
  ('Getting hospitalised, robbed, and divorced in the same Torn City day because of _______.', 1),
  ('Atomicc''s search history, leaked to the Council: _______.', 1),
  ('The Occultus faction ranking system goes: Recruit, Acolyte, Adept, Arcanist, Sentinel, Doomsayer, and _______.', 1);

-- ============================================================
-- FATE CARDS — Recon- specific
-- ============================================================
INSERT INTO cah_fate_cards (text, is_blank) VALUES
  ('Recon-, unconvincingly claiming he was just passing through', 0),
  ('Recon-''s six-hour "scouting mission" (he was at Maccas)', 0),
  ('Recon-''s intelligence report (it''s mostly doodles)', 0),
  ('Recon- arriving four hours late with a coffee and no apology', 0),
  ('Recon- being promoted for something he still won''t explain', 0),
  ('Whatever Recon- found that he''s not allowed to talk about', 0),
  ('Recon- insisting it was a tactical retreat', 0),

-- ============================================================
-- FATE CARDS — R18 / edgy / Torn / member-referenced
-- ============================================================
  ('VirginPimp69''s search history', 0),
  ('The girlsauce (still unidentified)', 0),
  ('Whatever Onenutwonder420 keeps in their jacket', 0),
  ('Thegimp13''s very specific hobbies', 0),
  ('HotChickOG''s method of earning respect that isn''t attacking', 0),
  ('An uncomfortable amount of physical contact during a war', 0),
  ('A conjugal visit from an enemy faction member', 0),
  ('The faction Discord after midnight on a Friday (do not scroll up)', 0),
  ('A full-body hospital examination that took suspiciously long', 0),
  ('Aggressive flirting with the Torn City judge', 0),
  ('Getting arrested and leaving a positive Yelp review', 0),
  ('The crime that was absolutely worth the jail sentence', 0),
  ('A fetish that somehow improves your war stats', 0),
  ('Three members, one hotel room, and no explanation whatsoever', 0),
  ('Whatever SnoopDoggyDogg is rolling before the chain', 0),
  ('Catching feelings for someone in the enemy faction mid-war', 0),
  ('The "special mission" that involved a burner phone and a motel', 0),
  ('A suspiciously detailed knowledge of Torn City''s red light district', 0),
  ('Selling your own faction members for drug money (it was worth it)', 0),
  ('The private Discord server that three Council members are in', 0),
  ('Screaming the wrong name during a war attack', 0),
  ('An inappropriate alliance with a very attractive enemy', 0),
  ('A war crime that technically isn''t against the rules', 0),
  ('Stabbing someone and immediately applying for their position', 0),
  ('Committing securities fraud to fund a chain', 0),
  ('Turning yourself in just to avoid the faction Discord', 0),
  ('A murder that everyone quietly agreed was completely justified', 0),
  ('Doing crimes purely for the aesthetic', 0),
  ('The hospital wing named after your most frequent patient', 0),
  ('A deeply personal attack on someone''s Torn City level', 0),
  ('The faction rule that definitely wasn''t there last week', 0),
  ('Two Doomsayers and a very bad idea', 0),
  ('Making questionable decisions at the Torn casino at 2am', 0),
  ('A full-body cavity search at the Torn City border (it was fine)', 0),
  ('The "team-building exercise" that HR never approved', 0),
  ('An erotic Torn City fanfic authored by someone in this room', 0),
  ('Recon-''s highly classified after-action report', 0),
  ('Atomicc''s browser history (the 3am tab specifically)', 0),
  ('A war declaration that was clearly motivated by a personal grudge', 0),
  ('The faction orgy that leadership officially calls a "strategic retreat"', 0),
  ('Discoball''s after-party (survivors only)', 0),
  ('The initiation ritual that nobody warned you about', 0),
  ('Mozz''s pre-war ritual (it involves nudity, allegedly)', 0),
  ('Forgeron''s incident report, redacted entirely except for the word "again"', 0),
  ('Smitty12 after three faction drinks vouchers', 0),
  ('A suspiciously enthusiastic prison visitor', 0),
  ('Night-Fury''s folder labelled "definitely not blackmail"', 0),
  ('The Torn City crime the police keep finding you at the scene of', 0),
  ('The thing KillroyJenkins killed and is no longer allowed to discuss', 0),
  ('GrimmLadd''s grim collection of things found in the faction vault', 0),
  ('An anonymous suggestion in the faction suggestion box (it was Recon-)', 0),
  ('The leaderboard you don''t want your name on (your name is on it)', 0),
  ('A safe word that nobody remembered in the moment', 0),
  ('Waking up in the Torn City hospital with no memory and a new tattoo', 0),
  ('The thing the Torn City police blotter describes as "unprecedented"', 0);
