-- Broad fate cards — versatile answers that work with most shadow card prompts
-- These are short noun/gerund phrases designed to fill any blank convincingly

INSERT INTO cah_fate_cards (text, is_blank) VALUES
  -- ── Concrete objects / items ──────────────────────────────────────────────
  ('A poorly timed screenshot', 0),
  ('An unsigned confession', 0),
  ('A handwritten resignation letter, unsent', 0),
  ('The receipt from that night', 0),
  ('A duffel bag with no questions attached', 0),
  ('A second phone with a second life', 0),
  ('A list of names that keeps getting longer', 0),
  ('A strongly-worded document that achieved nothing', 0),
  ('Evidence that nobody wanted to find', 0),
  ('The key that opens the door nobody should open', 0),
  ('A briefcase full of bad decisions', 0),
  ('The file marked "resolved" that is very much not resolved', 0),
  ('Something hidden in plain sight', 0),
  ('A favour with no stated price', 0),
  ('The only surviving copy of something that should have been destroyed', 0),

  -- ── Abstract concepts ─────────────────────────────────────────────────────
  ('Unshakeable confidence with zero basis', 0),
  ('The audacity', 0),
  ('Catastrophic miscalculation', 0),
  ('Plausible deniability', 0),
  ('Misplaced loyalty', 0),
  ('Barely contained chaos', 0),
  ('Existential dread at an inconvenient time', 0),
  ('A complete lack of self-awareness', 0),
  ('Unearned authority', 0),
  ('A vague sense that something is deeply wrong', 0),
  ('Consequences, eventually', 0),
  ('The point of no return', 0),
  ('The silence that follows a terrible idea', 0),
  ('The very last warning', 0),
  ('Wilful ignorance at a critical moment', 0),
  ('A decision made entirely in anger', 0),
  ('The thing nobody is willing to name out loud', 0),
  ('An extremely ill-timed sense of pride', 0),
  ('The part where everything went wrong', 0),
  ('A total and irreversible commitment to the bit', 0),

  -- ── Actions as noun phrases (gerunds) ─────────────────────────────────────
  ('Absolutely losing it at the worst possible moment', 0),
  ('Pretending nothing happened', 0),
  ('Blaming someone else (correctly)', 0),
  ('Making it everyone else''s problem', 0),
  ('Burning everything and starting fresh', 0),
  ('Agreeing out loud while disagreeing internally', 0),
  ('Screaming into the void (it responded)', 0),
  ('Showing up at the absolute worst time', 0),
  ('Being technically right and morally wrong', 0),
  ('Doing that and then immediately doing it again', 0),
  ('Walking in like nothing happened', 0),
  ('Watching it unfold and choosing not to intervene', 0),
  ('Denying everything with complete conviction', 0),
  ('Doubling down when backing out was still an option', 0),
  ('Taking credit for something you had no part in', 0),

  -- ── Dark / absurdist ──────────────────────────────────────────────────────
  ('At least two war crimes', 0),
  ('Violence, but politely', 0),
  ('The one thing you were specifically told not to do', 0),
  ('A body that no one is claiming', 0),
  ('The option that only sounds insane at first', 0),
  ('The favour you''ll regret calling in', 0),
  ('Whatever is making that noise', 0),
  ('The least bad choice available', 0),
  ('Something that used to be a person', 0),
  ('A murder that raised more questions than it answered', 0),
  ('The crime that isn''t in the rulebook yet', 0),
  ('Whatever that was, it worked', 0),
  ('A catastrophe that technically solved the original problem', 0),
  ('A threat delivered so calmly it was somehow worse', 0),
  ('The door you were told never to open (it''s open)', 0),

  -- ── Faction / Torn-tone ───────────────────────────────────────────────────
  ('A faction promotion with no salary attached', 0),
  ('Leaving mid-chain and blaming the WiFi', 0),
  ('The member who is definitely still active (they are not)', 0),
  ('A war declaration that surprised everyone, including the sender', 0),
  ('A faction rule added specifically because of one person', 0),
  ('The leader who went offline and never came back', 0),
  ('Reading the rules for the first time, mid-war', 0),
  ('Someone''s alt account doing something the main account can''t', 0),
  ('A warning that arrived three hours too late', 0),
  ('Getting promoted for something you still deny doing', 0),
  ('The thing you only admit to after leaving the faction', 0),
  ('Logging back in after three weeks and pretending to know what''s happening', 0),
  ('A recruitment pitch that was mostly threats', 0),
  ('The 3am faction message that changed everything', 0),
  ('The alliance that looked great on paper', 0);
