-- Member-referenced, Torn-specific, and Occultus-themed card expansion

-- Shadow Cards (prompts)
INSERT INTO cah_shadow_cards (text, picks) VALUES
  ('TugaRambo''s official pre-war briefing is one slide. It says _______.', 1),
  ('Before every chain, Viola_ sends a faction-wide message that just reads: "_______.".', 1),
  ('Discoball called an emergency meeting. The agenda item was _______.', 1),
  ('Atomicc''s 3am faction message: "Just a reminder that _______. Good night."', 1),
  ('Nobody talks about the time Forgeron accidentally _______.', 1),
  ('JSousa77''s leadership tip, slide 1 of 47: "Always remember _______.".', 1),
  ('The Council''s secret agenda item, buried at the bottom of every meeting: _______.', 1),
  ('Smitty12 was briefly removed from the faction Discord for _______.', 1),
  ('Forestbomb posted in faction chat at 3am: "_______." Still no context.', 1),
  ('Dragonlite joined the Council primarily to gain access to _______.', 1),
  ('KillroyJenkins has a well-documented reputation for _______. Nobody questions it.', 1),
  ('Noble_Squirrel was found in the faction vault with nothing but _______.', 1),
  ('MJPQR wrote a 47-page document titled "_______". Nobody has read it.', 1),
  ('The Ladd family''s unofficial faction motto is "_______".', 1),
  ('Night-Fury has a strict personal policy of _______ during all raids.', 1),
  ('PsychoticKingAJ''s faction bio is exactly one sentence: "_______.".', 1),
  ('Mozz insists on _______ before every war. Leadership has stopped arguing.', 1),
  ('SnoopDoggyDogg joined Occultus primarily for access to _______.', 1),
  ('The faction notice titled "This is NOT about Onenutwonder420" was actually about _______.', 1),
  ('ExeQtd''s written, notarised excuse for missing the chain: _______.', 1),
  ('DoneFeedingFox''s final message to the enemy faction before the war ended: "_______.".', 1),
  ('girlsauce replied to the chain notification with _______. It worked.', 1),
  ('Kelvalrogh''s management philosophy, summarised in one sentence: "_______.".', 1),
  ('IVerbYourNoun was asked to explain their username. The answer was _______.', 1),
  ('Merco was promoted to Archon on the strict condition they never again _______.', 1),
  ('The Torn City hospital''s most frequent admission reason this month: _______.', 1),
  ('_______ is the single leading cause of faction drama across all of Torn City.', 1),
  ('After 10 years in Torn City, the only thing you truly own is _______.', 1),
  ('The real meaning of "fair fight: 0.12" is _______.', 1),
  ('Getting mugged outside the Torn casino and finding _______ in your pockets.', 1),
  ('Torn City''s weekly maintenance always seems to fall during _______.', 1),
  ('The faction member who has been "travelling to Mexico" for three weeks is actually _______.', 1),
  ('FattyMatty''s war strategy document is 22 tabs long. Every tab contains _______.', 1),
  ('Sockrox opened the Council meeting with "_______." It set the tone immediately.', 1),
  ('GrimmLadd''s grim assessment of the situation: "_______".', 1);

-- Fate Cards (answers) — member-referenced
INSERT INTO cah_fate_cards (text, is_blank) VALUES
  ('TugaRambo in full war paint at 6am', 0),
  ('Atomicc managing the chain from a hospital bed', 0),
  ('Discoball''s pre-war playlist on full volume', 0),
  ('Noble_Squirrel''s extremely noble agenda', 0),
  ('girlsauce, unspecified', 0),
  ('VirginPimp69''s faction application essay', 0),
  ('Onenutwonder420''s notarised medical history', 0),
  ('The entire Ladd family arriving at once', 0),
  ('Forgeron, insisting nothing happened', 0),
  ('Night-Fury materialising from the void at full speed', 0),
  ('Viola_ sending a strongly-worded faction DM', 0),
  ('SnoopDoggyDogg, with absolutely no further context', 0),
  ('FattyMatty''s war spreadsheet (22 tabs, all blank)', 0),
  ('Merco''s official reason for being there', 0),
  ('IVerbYourNoun literally verbing your noun', 0),
  ('PsychoticKingAJ doing exactly what the name suggests', 0),
  ('JSousa77 opening a formal dispute about 4 respect points', 0),
  ('KillroyJenkins clearing their entire schedule for this', 0),
  ('Smitty12''s halftime motivational speech', 0),
  ('Thegimp13, present and accounted for', 0),
  ('DoneFeedingFox, who has in fact been feeding the fox this whole time', 0),
  ('GrimmLadd''s grim assessment of the situation', 0),
  ('ExeQtd-ing out of the chain mid-attack', 0),
  ('HotChickOG''s response to a hospital bill', 0),
  ('Kelvalrogh''s surprisingly effective management style', 0),
  ('Sockrox''s opening statement at the Council meeting', 0),
  ('MJPQR''s 47-page document that nobody asked for', 0),
  ('Mozz''s pre-war ritual that nobody is allowed to describe', 0),
  ('Dragonlite accessing something they shouldn''t have access to', 0),
  ('Forestbomb''s 3am faction message with zero context', 0),
  -- Torn-specific fate cards
  ('Spending 23 hours in hospital and calling it a strategy', 0),
  ('A "fair fight" bonus of 0.03', 0),
  ('Accidentally attacking your own faction officer', 0),
  ('The war starting at 3am your time, every single time', 0),
  ('The Torn casino eating your entire war fund', 0),
  ('A revive request that arrives 45 minutes after death', 0),
  ('Torn weekly maintenance happening at chain hit 998', 0),
  ('A booster that expired three years ago', 0),
  ('Getting mugged by a Level 1 recruit', 0),
  ('The faction member who has been "travelling" for six weeks', 0),
  ('Checking faction stats and immediately closing the tab', 0),
  ('An attack log that reads "stalemate" fourteen times in a row', 0),
  ('The nerve agent that somehow only affects your own faction', 0),
  ('Three members, one hospital, and a very unclear sequence of events', 0),
  ('The travel notification that arrives mid-attack', 0);
